print("Welcome to STEALING THE DIAMOND!")
print()
nome_gioco=input("Come ti chiami? ")
print("Benvenuto", nome_gioco)
print("Sei stato licenziato dal tuo posto di lavoro, i tuoi genitori ti hanno cecciato di casa e a vent'anni ti ritrovi solo come un cane abbandonato in mezzo a una strada.")
print("Un tuo caro amico in apprensione per la situazione ti ha informato che di lì a poco un carico di diamanti, tra cui il più grande ammonta a un milione di euro, sarà esposto nel museo della tua città.")
print("E' la tua occasione.")
print("Decidi così di seguire il consiglio del tuo amico e di provare a migliorare la tua condizione provando a rubare il diamante più costoso.")
print("Al calar del sole decidi finalmente di agire.")
print("Ti ritrovi dinnanzi al museo..")
print()
print("Cosa fai:")
print("1. Ti avvicini di soppiatto ")
print("2. Entri di prepotenza")
print()
prima_risposta=input()
if prima_risposta=="1":
  print()
  print("Ti avvicini silenziosamente, ma un muro ti ostacola.")
  print("Come lo oltrepassi?")
  print()
  print("1. Usufruisci di un piccone per aprire lentamente un varco nel muro")
  print("2. Utilizzi un paio di trampoli che ti eri portato nella borsa per raggiungere il tetto del museo")
  print("3. Utilizzi una vanga per scavare un passaggio sotterraneo")
  print()
  risposta_secondaria1=input()
  if risposta_secondaria1=="1":
    print()
    print("Ti ritrovi dentro la stanza dedicata ai reperti della seconda guerra mondiale.")
    print("Si parano di fronte a te due guardie che imbracciano un fucile...")
    input()
    print("Per fortuna non ti hanno visto.")
    print("Devi decidere in fretta, scegli uno tra questi tre oggetti:")
    print()
    print("1. Una ricostruzione in scala di un caccia tedesco radiotelecomandato")
    print("2. Una bomba ritrovata in Austria mai esplosa")
    print("3. Una baionetta ")
    print()
    risposta_operazione=input()
    print()
    if risposta_operazione=="1":
      print()
      print("Ti ricordi che in realtà non sai come si comanda un aeroplanino, ma ormai è troppo tardi e le guardie ti hanno già visto.")
      print("Ci sarai stato un milione di volte in questo museo e ormai la strada per arrivare alla stanza delle grandi esposizioni la sai a memoria. IL problema sono le due guardie che stanno correndo verso di te a fucili spianati ")
      print()
      print("Serve una manovra illusiva per distrarre le guardie.")
      print("PREMI 2 VOLTE LA D, 3 VOLTE LA W, UNA VOLTA LA A E 5 VOLTE LA W'")
      input()
      print("Fiuu, c'era mancato poco, ma per fortuna la tua manovra li ha abbindolati e hanno cominciato ad inseguire l'areopl...")
      input()
      print("Bz")
      print("Bzzzzz")
      print("L' AREOPLANINO STA TORNANDO INDIERO, E CON ALL'INTERNO IL DIAMANTE!")
    elif risposta_operazione=="2":
      print()
      print("Prendi in mano la bomba per colpire le guarde ma accidentalmente ti cade per terra facendo esplodere l'intero edificio, te compreso.")
      print()
    elif risposta_operazione=="3":
      print()
      print("Rompi il vetro della teca alla tua destra e afferri la baionetta.")
      print("Sperando sia carica la punti contro la prima guardia e fai esplodere il primo colpo.")
      print("La guardia si accascia a terra e il compagno lo va a soccorrere.")
      print("Cosa decidi di fare?")
      print()
      print("1. Spari alla guardia inginocchiata a terra ad aiutare il compagno")
      print("2. Scappi nell'altra stanza")
      print("3. Sapendo che il fucile sarà probabilmente scarico, decidi di lanciarlo a mo di lancia contro la restante guardia:")
      risposta_fucile=input()
      if risposta_fucile=="1":
        print()
        print("Provi a sparare ma ti accorgi che hai finito le cartucce, ma la guardia no e ti spara.")
        print()
      elif risposta_fucile=="2":
        print()
        print("Preso dalla foga del momento decidi di scappare non vedendo l'aereoplanino che avevi precedentemente abbandonato in mezzo alla stanza,inciapi su di esso infilzandoti con la baionetta.")
        print()
      elif risposta_fucile=="3":
        print()
        print("Riesci a mandare al tappeto anche la seconda guardia e approfittando del momento di caos favorevole, decidi di correre verso la stanza dei diamanti.")
        print("A tua grande sorpresa trovi la stanza sprovvista di guardie, impegnate a soccorrere le altre due ferite.")
        print("Ti avvicini al diamante, con mano tremolante provi provi ad afferrarlo pensando scatti l'allarme, la fortuna vuole avevano disattivato l'allarme per portare i due feriti in ospedale. ")
        print("IL DIAMANTE E'TUO!")
  elif risposta_secondaria1=="2":
    print()
    print("Ti allacci i trampoli e mentre fai l'ultimo passo per saltare finalmente sul tetto uno dei tue trampli si spezza, facendoti cadere rovinosamente al suolo, rompendoti l'osso del collo.")
  elif risposta_secondaria1=="3":
    print()
    print("Dopo aver scavato a lungo, sbuchi in un buio ripostiglio per le scope. Fuori dall'uscio senti una guardia che parla al walkit talkit.")
    print("Accendi la torcia e vedi che di fronte a te ci sono diversi oggetti")
    print()
    print("Tra cui:")
    print()
    print("1. Prendi un manico di scopa")
    print("2. Prendi un secchio di acqua e sapone")
    print("3. Utilizzi uno sgabello per salire nei condotti di eareazione")
    risposta_secondaria2=input()
    print()
    if risposta_secondaria2=="1":
      print()
      print("Esci dallo sgabuzzino e sicuro di te provi ad affrontare la guardia.")
      print("Ti avvicini e quando vi trovate faccia a faccia decidi di colpirlo.")
      print("Dove?")
      print()
      print("1. Alla gamba destra")
      print("2. in testa")
      print("3. Nelle parti intime")
      risposta_secondaria3=input()
      if risposta_secondaria3=="1" or "2" or "3":
        print()
        print("AIA!")
        input()
        print("Quello che hai appena colpito era Carlos, l'uomo delle pulizie di 52 anni.")
        print("Ad un certo punto, senti un individuo toccarti sulla spalla. Ti giri. E vedi la canna di pistola pistola davanti ai tuoi occhi.")
    elif risposta_secondaria2=="2":
      print()
      print("Hai la brillante idea di versare il contenuto del secchio sotto la porta, dimodo da far scivolare la guardia che stava camminando lì fuori.")
      print("Bell'idea, se non fosse che non riesci più ad uscire dallo sgabuzzino, bloccato dall'acqua.")
    elif risposta_secondaria2=="3":
      print()
      print("Una volta dentro ti si presentano davanti tre possibili strade")
      print("Dove decidi di andare?")
      print()
      print("1. Sinistra")
      print("2. Dritto")
      print("3. Destra")
      risposta_secondaria4=input()
      print()
      if risposta_secondaria4=="1":
        print()
        print("Ti trovi in un condotto che sembra non finire più, ad un certo punto, vedi finalmente la luce infondo al tunnen e abbagliato da quest'ultima incominci a correre verso l'uscita...")
        input()
        print("Il condotto portava direttamente al lato est del museo facendoti precipitare giù dalla montagna.")
      elif risposta_secondaria4=="2":
        print()
        print("Verso la metà del condotto, ti ritrovi sopra ad una grata. Ti chini per guardare attraverso le sbarre, quando una delle viti cede facendoti precipitare direttamente supre il tavolo della sala riunioni del museo, proprio durante un meeting del personale.")
      elif risposta_secondaria4=="3":
        print()
        print("Ti ritrovi nuovamnete di fronte ad un trivio.")
        print("Dove procedi?")
        print()
        print("1. Sinistra")
        print("2. Dritto")
        print("3. Destra")
        risposta_secondaria5=input()
        if risposta_secondaria5=="1":
          print()
          print("Verso la metà del condotto, ti ritrovi sopra ad una grata. Ti chini per guardare attraverso le sbarre, quando una delle viti cede facendoti precipitare direttamente supre il tavolo della sala riunioni del museo, proprio durante un meeting del personale.")
        elif risposta_secondaria5=="2":
          print()
          print("A furia di gattonare per il condotto, trovi finalmente la grata che stavi cercando.")
          print("Lo vedi è proprio sotto di te.")
          print("Sviti la grata e ti cali all'interno della stanza.")
          print("Con il naso direttamente sopra il diamante, decidi con uno scatto felino di afferrare il gioiello e, tramite i trampoli raggiungere nuovamente il bocchettone del condotto, per uscire sano e salvo con il tuo diamante da un milione di euro.")
        elif risposta_secondaria5=="3":
          print()
          print("Ti trovi in un condotto che sembra non finire più, ad un certo punto, vedi finalmente la luce infondo al tunnen e abbagliato da quest'ultima incominci a correre verso l'uscita...")
          input()
          print("Il condotto portava direttamente al lato est del museo facendoti precipitare giù dalla montagna.")
elif prima_risposta=="2":
  print("Ti ricordi che tuo zio ti aveva lasciato in eredità un panzer soldier ancora perfettamente funzionante. decidi così di provarlo sulla porta principale del museo, ma essendo che quel carro armato non veniva usato dalla seconda guerra mondiale, la canna si inceppa, facendo esplodere tutto.")
print()
print("FINE")
print("GRAZIE PER AVER GIOCATO A STEALING THE DIAMOND DI GABRIELE IOTTI & ALBERTO ZELIOLI!")